# Site settings
name: Desi European - Our Experiences with Life
description: "Experiences of a bunch of locals (as the term desi from India) who are living in Europe"

baseurl: "/Travelogue" # the subpath of your site, e.g. /blog
url: "http://desieuropean.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
relative_permalinks: false
permalink: :title/

pagination: true
paginate: 8
paginate_path: page/:num/

author:
    name: "Sushil Gulati"
    email: ""
    uri: "https://github.com/sushilgulati"

sass:
    sass_dir: _sass
    style: compressed

defaults:
    - scope:
          path: "_posts"
          type: "posts"
      values:
          reading_time: true
          # Meta
          show_tags: true
          show_categories: true
          # Social
          share_buttons: true
          disqus: true

plugins:
    - jekyll-feed
    - jekyll-paginate
    - jekyll-sitemap
